apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: three-tier
data:
  config.js: |
    window._env_ = {
      REACT_APP_BACKEND_URL: "http://192.168.49.2/api/tasks",
      NODE_ENV: "production"
    };
